/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Admin": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Ai": {
      "chatModelId": string
      "dataSourceId": string
      "embeddingModelId": string
      "knowledgeBaseId": string
      "type": "sst.sst.Linkable"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CorpusBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Database": {
      "clusterArn": string
      "database": string
      "secretArn": string
      "type": "sst.sst.Linkable"
    }
    "DatabaseMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Realtime": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "RealtimePublish": {
      "authorizer": string
      "endpoint": string
      "type": "sst.sst.Linkable"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}

import "sst"
export {}